### ISSUE TITLE
Copilot Command Implementation Tracker

### ISSUE THREAD

**Issue by TerminalFi** [TerminalFi/LSP-copilot#21]
### What

Track all commands which are defined by Copilot and track implementation status

- [ ] `httpRequest`
- [ ] `recordTelemetryConsent`
- [ ] `notifyShown`
- [ ] `debug/verifyState`
- [ ] `debug/verifyWorkspaceState`
- [x] `getCompletions`
- [x] `getPanelCompletions` (#18)
- [x] `getCompletionsCycling` (#29)
- [x] `getVersion`
- [x] `setEditorInfo`
- [x] `checkStatus`
- [x] `signInInitiate`
- [x] `signInConfirm`
- [x] `signOut`
- [x] `notifyAccepted`
- [x] `notifyRejected`
- [x] ~~`telemetry/exception`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/createContext`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/alwaysAuth`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/neverAuth`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/useTestingToken`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/setCompletionDocuments`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/setPanelCompletionDocuments`~~ __*WONT IMPLEMENT*__
- [x] ~~`testing/triggerShowMessageRequest`~~ __*WONT IMPLEMENT*__

**Comment by jfcherng** [comment]
>  "getCompletionsCycling"
Currently we cycle completions as they are populated. However, we don't actually send a request to getCompletionCycling. getCompletionCycling actually tells Copilot to return a list of possible completions. We should implement this properly @jfcherng

Do you know what's the correct working flow? I tried to send `getCompletionCycling` instead of `getCompletion` and I see no difference.

**Comment by jfcherng** [comment]
Sounds like we have to send both `getCompletion` and `getCompletionCycling` all at once? We don't have a UI to let user request for more completions.

**Comment by TerminalFi** [comment]
Closing as the majority are implemented and I don't believe the remaining need to be considered
